### ISSUE TITLE
Error when deploy to ibm cloud

### ISSUE THREAD

**Issue by vrcrush** [IBM/watson-voice-bot#15]
I followed your instructions to deploy to IBM cloud
getting error in Deploy Stage

Creating route watson-voice-bot.mybluemix.net...
OK

FAILED
Server error, status code: 400, error code: 210003, message: The host is taken: watson-voice-bot

Finished: FAILED

**Comment by vrcrush** [comment]
modified the manifest

**Comment by stevemart** [comment]
@vrcrush what changes did you make to the manifest? It would be great to have the result here should others stumble upon a similar problem.

**Comment by vrcrush** [comment]
hi @stevemart , it is a good idea. sorry!

I modified file mafiest.yml , i changed the the name and host values under the applications section.
You can use any other name

**Comment by ishank-dev** [comment]
In order to make changes, I cloned the repository so how should I proceed with it now?
