### ISSUE TITLE
Enhancing client app to use npm

### ISSUE THREAD

**Issue by sanjeevghimire** [IBM/watson-voice-bot#18]
Current Problem:
* watson-speech.js is a copy of node sdk - this way its hard to upgrade to latest
* the auth token support will no longer be there when cloudfoundry instances will be deprecated. The auth token api doesn't work right now. [bug]

Proposed Refactoring:
* make static folder an node app where dependencies are managed by npm. This way upgrading to latest SDK , extending and maintaining the app would be easier.
* Fix auth token issue by not using auth token api any more.

**Comment by dolph** [comment]
This is potentially a blocker for #20 and indirectly the root cause of that issue.

**Comment by markstur** [comment]
I don't think this applies to the current code.  It uses python Watson SDK.
