### ISSUE TITLE
Local Apikey authentification not implemented

### ISSUE THREAD

**Issue by haukesand** [IBM/watson-voice-bot#20]
Text to speech and speech to text apikeys are not loaded in the welcome.py

However .env authentification encourages to use them. 
TEXTTOSPEECH_IAM_APIKEY=
SPEECHTOTEXT_IAM_APIKEY=

**Comment by dolph** [comment]
A similar report from Hania Ibrahim:

> I'm facing some trouble with Text to Speech and Speech to Text when I use the Frankfurt region or any other region as they use IAM keys and the AuthorizationV1 doesn't seem to recognize the IAM keys in order to create the token.

**Comment by dolph** [comment]
According to @sanjeevghimire, fixing this elegantly requires addressing #18

**Comment by dalmago** [comment]
I think the branch `iam-changes` solves this, at least for running the application locally.

**Comment by dolph** [comment]
This was fixed in https://github.com/IBM/watson-voice-bot/pull/25
