### ISSUE TITLE
Receiving this message when deploying : Error restarting application: Start unsuccessful

### ISSUE THREAD

**Issue by fatemaRam** [IBM/watson-voice-bot#21]
![image](https://user-images.githubusercontent.com/45220705/48817020-61bf8f00-eda9-11e8-8a9b-55f21cc83e0f.png)
Previously had this error: 
Creating route watson-voice-bot.mybluemix.net...
OK

FAILED
Server error, status code: 400, error code: 210003, message: The host is taken: watson-voice-bot

but fixed that by changing the name and host in the manifest applications, but am now running the error in the image above

**Comment by josecarlossml** [comment]
i have this problem too

**Comment by sanjeevghimire** [comment]
@fatemaRam can you please share the logs by running the last command in the image you sent?

**Comment by fatemaRam** [comment]
Hi how do I run that command? I’ve installed cloud CLI but when I enter the command in the cmd it says the command cf doesn’t exist ?
Thanks so much for your help

**Comment by dolph** [comment]
@fatemaRam To use the `cf` CLI, you just need to [download](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html) it and [login](https://docs.cloudfoundry.org/cf-cli/getting-started.html#login).

**Comment by dalmago** [comment]
Same problem here. Got the following logs:

[APP/PROC/WEB/0] ERR Traceback (most recent call last):
[APP/PROC/WEB/0] ERR   File "welcome.py", line 39, in <module>
[APP/PROC/WEB/0] ERR     assistantUsername = conversationCreds['username']
[APP/PROC/WEB/0] ERR KeyError: 'username'
[APP/PROC/WEB/0] OUT Exit status 1
[CELL/SSHD/0] OUT Exit status 0

**Comment by dalmago** [comment]
I also accessed the environment variables, and it has the **apikey** and **url** for each service, but not **username** and **password** as the `welcome.py` expects. 

Related to #18?

**Comment by dalmago** [comment]
Maybe this is a working solution:
https://github.com/IBM/watson-voice-bot/compare/master...dalmago:master

**Comment by dolph** [comment]
Based on the above, it sounds to me like this was fixed in https://github.com/IBM/watson-voice-bot/commit/074d2f8d2818743c62b5ba86ba409c59e1a51b12 - comment if that's not the case, and we'll re-open this. Thanks!

**Comment by Tayeb60** [comment]
Please help. when I run: 
%%bash
ibmcloud target --cf-api https://api.eu-gb.cf.cloud.ibm.com -r eu-gb -o tayeeb@hotmail.co.uk
ibmcloud account space-create computer-vision-app
ibmcloud cf

I get this error message:

FAILED
Error response from server. Status code: 400; description: 40002 The following error occurred in the region 'London': The app space name is taken: computer-vision-app.

**Comment by rhagarty** [comment]
@Tayeb60 did you try changing the app space name?
