### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by martinsteinorth** [IBM/watson-voice-bot#32]
Giving the demo a try I found that the description in the README seems to be older. The code still works, but to save others some time two things should be mentioned:

**Deployment Error**

```
Creating route watson-voice-bot.eu-gb.mybluemix.net...
OK

FAILED
Server error, status code: 400, error code: 210003, message: The host is taken: watson-voice-bot
```

Fix: Change name and host to something unique

https://github.com/IBM/watson-voice-bot/blob/23c5116031978bbc69c61d24f6f10394f1b9ec93/manifest.yml#L17
https://github.com/IBM/watson-voice-bot/blob/23c5116031978bbc69c61d24f6f10394f1b9ec93/manifest.yml#L18

**Workspace ID vs Assistant ID and API Key**

The example code uses v1 of the Assistant API so you have to get the Workspace ID instead of the Assistant ID of the **skill**. You have to get the API Key as well.

See https://cloud.ibm.com/apidocs/assistant for detailed information.

**Comment by stevemart** [comment]
@martinsteinorth thanks! i'll have someone do an overview of the README. We're aware of the change to Workspace ID and Assistant ID, we're updating all IBM assets to reflect that.

**Comment by stevemart** [comment]
poke @scottdangelo

**Comment by juanpablo64** [comment]
some parts are still outdated,  I can't find anything related to enviroment variables on IBM

**Comment by markstur** [comment]
new version coming soon

**Comment by juanpablo64** [comment]
thank you! definitely looking forward to it!!!!
