### ISSUE TITLE
I can not get it to work

### ISSUE THREAD

**Issue by CNeira7** [IBM/watson-voice-bot#43]
Hi I need help, please. Is implemented, the link is created, the text appears, but does not speak, I allow microphone but it does not take the audio. I have followed the steps, seen the videos and I do not know what the mistake is.

I follow the github guide, later I create IBM Cloud API Key: in Dallas.

Getting started with the IBM Cloud CLI
https://cloud.ibm.com/docs/cli?topic=cloud-cli-ibmcloud-cli&locale=en-US#overview

Then: Download, modify, and redeploy your Cloud Foundry app with the command line interface.

Change to the directory where your code is located.
cd your_new_directory

Connect and log in to IBM Cloud.
ibmcloud api https://api.ng.bluemix.net

bluemix app push watson-voice-bot-3
Access your app by browsing to https://watson-voice-bot-3-insightful-gnu.mybluemix.net.

**Comment by markstur** [comment]
The app and readme have been updated and tested.
There is no "bluemix app push" so I'd suggest starting over with the latest instructions.
