### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by EmilyLarkin00** [IBM/watson-voice-bot#44]
I have succesfully deployed the app and got it working in Chrome, however when I speak to the app I get 'Internal Server Error' as the response with "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application." below. 

I'm really very new to all this so can someone point me in the right direction to get this fixed? 

Thanks.

**Comment by juanpablo64** [comment]
hey emily, I am receiving the same error, can you give me any tips? did you perhaps found this error message?

local variable 'response' referenced before assignment
