### ISSUE TITLE
Multiple and option responses do not work

### ISSUE THREAD

**Issue by dinhtuan1004** [IBM/watson-voice-bot#45]
The bot works quite good. However, it does not say (and show) multiple responses and responses with options. It can recognize the intents relating to these responses and answers in a good manner as designed. For examples: there should be some responses after the sentence "I can help you with..... as follows". I am using lite plans for all services. 

![Screenshot (755)](https://user-images.githubusercontent.com/49051208/61678557-5b652680-ad2d-11e9-885b-ef5d218f0f33.png)

**Comment by markstur** [comment]
I have a fix by concatenating the multiple responses.  I think this covers "multiple options" but if it doesn't I need more details on that part.
