### ISSUE TITLE
ESLINT errors not solvable without refactoring

### ISSUE THREAD

**Issue by sanjeevghimire** [IBM/watson-voice-bot#5]
Please lint the javascript code and make sure travis passes when linting. Example of issues are:

<img width="722" alt="screen shot 2018-07-26 at 4 19 43 pm" src="https://user-images.githubusercontent.com/1693915/43289175-bfe88da0-90ef-11e8-9708-1bf1e6ee90ac.png">

**Comment by stevemart** [comment]
@sanjeevghimire what do you think of https://github.com/IBM/watson-voice-bot/pull/6 ?

**Comment by sanjeevghimire** [comment]
#6 fixes the spacing issue but not object referenced issues. if we hook eslint with travis, it will complain.

**Comment by stevemart** [comment]
@sanjeevghimire i created PR #8 too, just poking around with `eslint`.

Hi @ptrikkur can you look at #6 and #8

**Comment by ptrikkur** [comment]
@stevemart I merged both #6 and #8 . I took the resulting script.js and linted it. I got one error.

  1:5  error  Parsing error: Unexpected token conversationContext

✖ 1 problem (1 error, 0 warnings)

**Comment by sanjeevghimire** [comment]
@ptrikkur I have fixed the linting issues. I have also removed few unused functions, if you can review it as well that would be great. #9

**Comment by sanjeevghimire** [comment]
i think this is fixed. closing it.
